Parameterize library versions in install-sqoop script.
The install-sqoop script now accepts optional parameters:

* --hadoop-version (defaults to 1.0.0)
* --sqoop-version (defaults to 1.4.6)
* --mysql-connector-version (defaults to 5.1.35)

diff --git a/batch/bootstrap/install-sqoop b/batch/bootstrap/install-sqoop
--- a/batch/bootstrap/install-sqoop
+++ b/batch/bootstrap/install-sqoop
@@ -2,17 +2,37 @@
 
 set -e
 
-APACHE_MIRROR=www.apache.org
-HADOOP_VERSION=1.0.0
 BASE_PATH=$1
+shift
 
-SQOOP_VERSION=1.4.6
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --hadoop-version=*)
+      HADOOP_VERSION=${1#*=}
+      ;;
+    --sqoop-version=*)
+      SQOOP_VERSION=${1#*=}
+      ;;
+    --mysql-connector-version=*)
+      MYSQL_CONNECTOR_VERSION=${1#*=}
+      ;;
+    *)
+      printf "Error: Invalid argument: %s\n" "$1"
+      exit 1
+  esac
+  shift
+done
+
+APACHE_MIRROR=www.apache.org
+HADOOP_VERSION=${HADOOP_VERSION:-1.0.0}
+SQOOP_VERSION=${SQOOP_VERSION:-1.4.6}
 SQOOP_RELEASE=sqoop-$SQOOP_VERSION.bin__hadoop-$HADOOP_VERSION
 SQOOP_RELEASE_FILENAME=$SQOOP_RELEASE.tar.gz
 SQOOP_HOME=/usr/lib/sqoop
 SQOOP_LIB=$SQOOP_HOME/lib
 
-MYSQL_CONNECTOR_RELEASE=mysql-connector-java-5.1.35
+MYSQL_CONNECTOR_VERSION=${MYSQL_CONNECTOR_VERSION:-5.1.35}
+MYSQL_CONNECTOR_RELEASE=mysql-connector-java-$MYSQL_CONNECTOR_VERSION
 MYSQL_CONNECTOR_FILENAME=$MYSQL_CONNECTOR_RELEASE.tar.gz
 MYSQL_CONNECTOR_S3_URL=$BASE_PATH/$MYSQL_CONNECTOR_FILENAME
 
